Add home page "REUPLOAD"
asadt93/olshopq-practice-app pull request #3
Opened 2021-04-29 06:19 UTC by ezza-nidlomuddin

2021-04-29 06:20 UTC, ezza-nidlomuddin commented
Lek Aat , Ini Yang Asli, Tadi lupa Ku commit

2021-04-29 14:54 UTC, asadt93 requested changes
ini diubah yg tak komentari

2021-04-29 14:54 UTC, asadt93 commented on app/views/home/index.html.erb
> +                    <div class="card p-0 m-auto mb-3" style="width: 219px;">
kalo banyak yg pake style="width: 219px;" mending dibuat class aja

2021-04-29 14:54 UTC, asadt93 commented on config/database.yml
> +  username: ezzawa
ini itu username sama password nya ngikut di paling bawah 
```production:
  <<: *default
  database: olshopq_practice_app_production
  username: olshopq_practice_app
  password: <%= ENV['OLSHOPQ_PRACTICE_APP_DATABASE_PASSWORD'] %>```
  jadi yg di development: sama test: gak usah di tambahin, cuma 1x aja di paling bawah di production

2021-04-29 14:54 UTC, asadt93 commented on config/database.yml
> -  username: olshopq_practice_app
ini jangan di hapus
kamu coba pake gem figaro
nanti disana di set di 
# config/application.yml

OLSHOPQ_PRACTICE_APP_DATABASE_USERNAME: "ezzawa"
OLSHOPQ_PRACTICE_APP_DATABASE_PASSWORD: "2008"

nanti disini tinggal disi

```
username: ENV['OLSHOPQ_PRACTICE_APP_DATABASE_USERNAME']
password: ENV['OLSHOPQ_PRACTICE_APP_DATABASE_PASSWORD']
```

kenapa harus gitu, karena team developer nanti username dan password database ny gak sama
dan nanti application.yml kena gitignore jadi ga bisa di push
jadinya tiap developer harus bikin sendiri2 di isi sesuai data masing2

2021-04-30 01:30 UTC, ezza-nidlomuddin commented on app/views/home/index.html.erb
> +                    <div class="card p-0 m-auto mb-3" style="width: 219px;">
Iya Lek

2021-04-30 01:30 UTC, ezza-nidlomuddin commented on app/views/home/index.html.erb
> +                    <div class="card p-0 m-auto mb-3" style="width: 219px;">
Iya Lek

2021-04-30 01:31 UTC, ezza-nidlomuddin commented on config/database.yml
> +  username: ezzawa
ok

2021-04-30 03:16 UTC, ezza-nidlomuddin commented on config/database.yml
> +  username: ezzawa
maksudnya gimana lek?

2021-04-30 11:18 UTC, asadt93 commented on config/application.yml
> +production:
gak usah dikasih environment production
langsung aja
```
OLSHOPQ_PRACTICE_APP_DATABASE_USERNAME: "ezzawa"
OLSHOPQ_PRACTICE_APP_DATABASE_PASSWORD: "2008"
```

2021-04-30 11:18 UTC, asadt93 commented on config/database.yml
> +  username: ezzawa
trs ini hapus

2021-04-30 11:18 UTC, asadt93 commented on config/database.yml
> +  password: 2008
ini juga hapus, trs coba bisa gak

2021-04-30 11:20 UTC, ezza-nidlomuddin commented on config/database.yml
> +  password: 2008
di rails s?

2021-04-30 13:51 UTC, ezza-nidlomuddin commented on config/database.yml
> +  password: 2008
error lek
![image](https://user-images.githubusercontent.com/83116996/116704638-d6c13500-a9f5-11eb-975e-5fa76acd7aae.png)

2021-04-30 16:26 UTC, asadt93 commented on config/database.yml
> +  password: 2008
config/application.yml mu itu tetep isi lah, yg dibaca kan itu,
yg config/application.example.yml itu cuma contoh buat di isi team programer lain nantinya

2021-04-30 16:29 UTC, asadt93 commented on config/application.yml
> -  OLSHOPQ_PRACTICE_APP_DATABASE_USERNAME: "ezzawa"
ini tu jangan di hapus, orang di local mu baca nya ini

2021-04-30 16:29 UTC, asadt93 commented on .gitignore
> +/config/application.yml
harusnya kalo udah di kasih ini, gak bisa di push application.yml nya

2021-05-01 03:34 UTC, ezza-nidlomuddin commented on config/database.yml
> +  password: 2008
sudah

2021-05-01 09:39 UTC, ezza-nidlomuddin reviewed
```
development:
  <<: *default
  database: olshopq_practice_app_development
  username: <%= ENV['OLSHOPQ_PRACTICE_APP_DATABASE_USERNAME'] %>
  password: <%= ENV['OLSHOPQ_PRACTICE_APP_DATABASE_PASSWORD'] %>
```
  
  **Iki Lek, kutambahkan di development karena kalau tidak ku tulis muncul error tadi**

2021-05-01 09:47 UTC, ezza-nidlomuddin commented on config/database.yml
> +
Tak Tambahin di development, karena kalau di production saja, gak bisa, error

2021-05-02 07:56 UTC, merged