Add: Authentication Page in Admin
asadt93/olshopq-practice-app pull request #5
Opened 2021-06-05 14:51 UTC by ezza-nidlomuddin

2021-06-08 03:41 UTC, asadt93 requested changes
tanda2 conflict itu cari dan perbaiki dulu za

2021-06-08 03:41 UTC, asadt93 commented on Gemfile
> +>>>>>>> 4a46e554a89344b5cef9df188b0853d7f81d343e
ini di perbaiki

2021-06-08 03:41 UTC, asadt93 commented on Gemfile.lock
> +<<<<<<< HEAD
ini di perbaiki

2021-06-08 03:41 UTC, asadt93 commented on Gemfile.lock
> +>>>>>>> 4a46e554a89344b5cef9df188b0853d7f81d343e
ini di perbaiki

2021-06-08 03:41 UTC, asadt93 commented on Gemfile.lock
> +<<<<<<< HEAD
ini di perbaiki

2021-06-08 03:41 UTC, asadt93 commented on app/controllers/application_controller.rb
> +<<<<<<< HEAD
ini di perbaiki

2021-06-08 03:41 UTC, asadt93 commented on app/controllers/application_controller.rb
> +=======
ini di perbaiki

2021-06-08 03:41 UTC, asadt93 commented on app/controllers/application_controller.rb
> +>>>>>>> 4a46e554a89344b5cef9df188b0853d7f81d343e
ini di perbaiki

2021-06-08 03:42 UTC, ezza-nidlomuddin commented on app/controllers/application_controller.rb
> +>>>>>>> 4a46e554a89344b5cef9df188b0853d7f81d343e
iya lek

2021-06-10 00:18 UTC, ezza-nidlomuddin commented
Wes bar Lek

2021-06-10 02:44 UTC, asadt93 commented on config/application.example.yml
> -OLSHOPQ_PRACTICE_APP_DATABASE_USERNAME: "postgres"
ini kenapa di hapus?

2021-06-10 02:45 UTC, ezza-nidlomuddin commented on config/application.example.yml
> -OLSHOPQ_PRACTICE_APP_DATABASE_USERNAME: "postgres"
oh iya, tak ubah application.example.yml nya jadi application.yml

2021-06-10 02:45 UTC, ezza-nidlomuddin commented on config/application.example.yml
> -OLSHOPQ_PRACTICE_APP_DATABASE_USERNAME: "postgres"
tak buat copynya kalau begitu

2021-06-10 02:46 UTC, asadt93 requested changes
sama kasih video demo nya dari login sampe add edit delete categories

2021-06-10 02:47 UTC, ezza-nidlomuddin commented
Ok

2021-06-10 02:49 UTC, ezza-nidlomuddin commented
videonya taruh dimana?

2021-06-10 03:11 UTC, ezza-nidlomuddin commented
Udah Lek Di **Deskripsi**

2021-06-16 09:35 UTC, ezza-nidlomuddin commented
https://user-images.githubusercontent.com/83116996/122195617-b9bac580-cec0-11eb-8c8e-6278e7fa39a9.mp4

2021-06-16 10:07 UTC, asadt93 approved these changes
LGTM :+1:

2021-06-16 13:09 UTC, ezza-nidlomuddin commented
Thanks. And I close The PR right now

2021-06-16 13:09 UTC, closed without merging